<%-- Do not edit this file directly. See README.md --%>
<div class="row">
  <div class="col-sm-12">
    <h6></h6>
    <div class="col-sm-12 my-3 table-responsive">
      <table class="display table table-striped table-bordered table-sm datasets">
        <thead>
          <tr>
            <th>Database</th>
            <th>Download</th>
            <th>Type</th>
            <th>Interactions</th>
            <th>Interactors</th>
            <th>PMID</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span style="white-space:nowrap"><a href="https://academic.oup.com/nar/article/29/1/242/1116175">BIND</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FBIND&amp;files=BIND.sig" title="BIND.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>25622</td>
            <td>5528</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/12519993" title="12519993" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://www.biocarta.com/genes/index.asp">Biocarta</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FBiocarta&amp;files=Biocarta.sig" title="Biocarta.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>756</td>
            <td>352</td>
            <td></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="https://downloads.thebiogrid.org/BioGRID/Release-Archive/BIOGRID-3.4.154/">BioGRID</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FBioGRID&amp;files=BioGRID_filtered_ppi_2018_02_26.sig" title="BioGRID_filtered_ppi_2018_02_26.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mixed</td>
            <td>68759</td>
            <td>7312</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/27980099" title="27980099" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://bioplex.hms.harvard.edu/downloadInteractions.php">BioPLEX</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FBioPLEX&amp;files=BioPLEX_ppi_2017_06_07.sig" title="BioPLEX_ppi_2017_06_07.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mass-spec</td>
            <td>56553</td>
            <td>8610</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/26186194" title="26186194" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://dip.mbi.ucla.edu/dip/">DIP</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FDIP&amp;files=DIP_filtered_ppi_2017_07_12.sig" title="DIP_filtered_ppi_2017_07_12.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>3822</td>
            <td>1946</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/11752321" title="11752321" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">figeys</span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2Ffigeys&amp;files=figeys.sig" title="figeys.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mass-spec</td>
            <td>6452</td>
            <td>2033</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/17353931" title="17353931" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://www.hprd.org">HPRD</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FHPRD&amp;files=HPRD.sig" title="HPRD.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>47496</td>
            <td>7490</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18988627" title="18988627" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://proteincomplexes.org">huMAP</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FhuMAP&amp;files=huMAP.sig" title="huMAP.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mass-spec</td>
            <td>62214</td>
            <td>6061</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/28596423" title="28596423" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://www.innatedb.com">InnateDB</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FInnateDB&amp;files=innateDB_filtered_ppi_2017_07_12.sig" title="innateDB_filtered_ppi_2017_07_12.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>4576</td>
            <td>1523</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/23180781" title="23180781" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="https://www.ebi.ac.uk/intact/">IntAct</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FIntAct&amp;files=IntAct_filtered_ppi_2017_07_13.sig" title="IntAct_filtered_ppi_2017_07_13.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mixed</td>
            <td>15726</td>
            <td>4186</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/24234451" title="24234451" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/22121220" title="22121220" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://irefindex.org/wiki/index.php?title=iRefIndex http://wodaklab.org/iRefWeb/">iREF</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FiREF&amp;files=iREF_02-2018_Mouse-Human_KINASES_PPI.sig" title="iREF_02-2018_Mouse-Human_KINASES_PPI.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mixed</td>
            <td>28417</td>
            <td>5403</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18823568" title="18823568" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://www.kegg.jp">KEGG</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FKEGG&amp;files=KEGG.sig" title="KEGG.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>13993</td>
            <td>1198</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/19880382" title="19880382" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="https://mint.bio.uniroma2.it">MINT</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FMINT&amp;files=MINT-03-2018_Mouse-Human_PPI.sig" title="MINT-03-2018_Mouse-Human_PPI.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>75065</td>
            <td>9415</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22096227" title="22096227" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/24234451" title="24234451" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://mips.helmholtz-muenchen.de/proj/ppi/">MiPS</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FMiPS&amp;files=MIPS.sig" title="MIPS.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mass-spec</td>
            <td>606</td>
            <td>373</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/9399795" title="9399795" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/15531608" title="15531608" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://abc.med.cornell.edu/pdzbase">PDZbase</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FPDZbase&amp;files=pdzbase.sig" title="pdzbase.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>244</td>
            <td>159</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/15513994" title="15513994" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://www.PPID.mvm.ed.ac.uk">PPID</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FPPID&amp;files=ppid.sig" title="ppid.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>6998</td>
            <td>1208</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/14755292" title="14755292" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://www.maayanlab.net/S2N/">Sets2Networks</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FSets2Networks&amp;files=predictedPPI.sig" title="predictedPPI.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Predicted</td>
            <td>3000</td>
            <td>828</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22824380" title="22824380" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="https://code.google.com/archive/p/snavi/">SNAVI</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FSNAVI&amp;files=SNAVI.sig" title="SNAVI.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Literature PPI</td>
            <td>2007</td>
            <td>442</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/19154595" title="19154595" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/16169070">Stelzl</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FStelzl&amp;files=Stelzl.sig" title="Stelzl.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Mass-spec</td>
            <td>6207</td>
            <td>1702</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/16169070" title="16169070" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap"><a href="http://interactome.dfci.harvard.edu/H_sapiens/">Vidal</a></span></td>
            <td><span style="white-space:nowrap"><a href="http://amp.pharm.mssm.edu/lincs-playground/index.php/s/kuUSjyFOryhTRDv/download?path=%2FPPI%2FVidal&amp;files=vidal.sig" title="vidal.sig" style="padding-left:5px"><svg viewBox="-5 -5 110 131" preserveAspectRatio="xMinYMin" style="width:18px;position:relative;top:5px"><path d="M0,0 l75,0 l25,25 l0,100 l-100,0 z" fill="lightgrey" stroke="black" stroke-width="5"></path><path d="M5,75 l90,0 l0,45 l-90,0 z" fill="darkgrey" stroke="darkgrey" stroke-width="5" opacity="0.75"></path><g opacity="0.8"><path d="M30,10 l40,0 l0,45 l-40,0 z" fill="black"></path><path d="M15,40 l70,0 l-35,35 z" fill="black"></path></g><text font-size="3em" font-family="sans-serif" fill="black" text-anchor="middle" x="50" y="115" dx="0">SIG</text></svg></a></span></td>
            <td>Yeast-2-Hybrid</td>
            <td>6726</td>
            <td>2541</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/16189514" title="16189514" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>